import './globals.css'
import { Inter, K2D } from 'next/font/google'

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' })
const k2d = K2D({ subsets: ['latin'], weight: ['100', '200', '300', '400', '500', '600', '700', '800'], variable: '--font-k2d'})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${k2d.className}`}>{children}</body>
    </html>
  )
}
